# the BioSample accession
biosample_accession: SAMN46431257

# name of CSV file listing barcode runs to uploade
barcode_runs: ./barcode_runs_upload.csv

# the following come from the SRA FTP upload instructions
ftp_username: subftp
ftp_account_folder: uploads/tyler.n.starr_gmail.com_weG0ArpC

# Meaningful name for this sample's FTP folder:
ftp_subfolder: sarbecovirus_imprinted-serum-profiling
